### ISSUE TITLE
Serialize.Linq

### ISSUE THREAD

**Issue by esskar** [davidfowl/DynamicLinq#5]
Hi David,

thanks for that. Are you aware of my library, it is similar, but let's you serialize expressions, send them directly over WCF, and evaluate them on the server.

https://github.com/esskar/Serialize.Linq

Regards,
Sascha

**Comment by davidfowl** [comment]
Wow that's awesome (except for the WCF part) Why not a lightweight x-plat protocol instead?

**Comment by davidfowl** [comment]
Oh just read that it supports JSON, that's awesome

**Comment by esskar** [comment]
Yes, can you add own serializer implementations as well. Thanks.

**Comment by StefH** [comment]
Hi @esskar ; this library gives a perfect opportunity to convert to the new VS2015 (dnx/.net) core structure, so that you can have 1 project which just outputs .net 40, .net 45, sl and dnxcore50.

I'm willing to start on this, however do you have time (and do you want) to merge my forked project changes back to your project ?

Or should I just create a copy and totally fork away ?

See also my question at https://github.com/esskar/Serialize.Linq/issues/72

**Comment by esskar** [comment]
full support for .net standard 1.3 and 2.0
thanks to @StefH
